### ISSUE TITLE
RuntimeError: result type Float can't be cast to the desired output type Long

### ISSUE THREAD

**Issue by Haider182** [AlphaPav/DBA#12]
![image](https://github.com/AI-secure/DBA/assets/140696550/9832cf25-0949-4adc-910e-700ec56749b0)
I got an error while running this code in helper.py.  Please Help

Traceback (most recent call last):
  File "C:\Users\User\Desktop\backdoor\dba_distributed_backdoor_attac\DBA-master\DBA-master\main.py", line 177, in <module>
    is_updated = helper.average_shrink_models(weight_accumulator=weight_accumulator,
  File "C:\Users\User\Desktop\backdoor\dba_distributed_backdoor_attac\DBA-master\DBA-master\helper.py", line 256, in average_shrink_models
    data.add_(update_per_layer)
RuntimeError: result type Float can't be cast to the desired output type Long

**Comment by LukeZane118** [comment]
For me, I modify lines 69-70 of the code in the 'image_helper.py' file like this:
Before:
```
self.local_model = local_model
self.target_model = target_model
```
After:
```
self.local_model = local_model.type(torch.float)
self.target_model = target_model.type(torch.float)
```
And it seems to be running well.
